id: HelloWorld_Test
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: HelloWorld_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 16678589-7030-4738-8390-0b7dd84c2d74
    type: start
    task:
      id: 16678589-7030-4738-8390-0b7dd84c2d74
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: e3249b63-41f0-4099-886f-ac634c9fc7c6
    type: regular
    task:
      id: e3249b63-41f0-4099-886f-ac634c9fc7c6
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 502c4619-ad80-45b9-89bd-bb8334511625
    type: regular
    task:
      id: 502c4619-ad80-45b9-89bd-bb8334511625
      version: -1
      name: Helloworld
      description: Hello command - prints hello to anyone.
      script: HelloWorld1|||helloworld-say-hello
      type: regular
      iscommand: true
      brand: HelloWorld1
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      extend-context:
        simple: test=
      name:
        simple: shlan
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 385
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 6886b4e8-7838-4bf3-8246-27bc1f2fbbe5
    type: condition
    task:
      id: 6886b4e8-7838-4bf3-8246-27bc1f2fbbe5
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: hello
            iscontext: true
          right:
            value:
              simple: Hello shailan
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 2d0a1722-dbad-417a-8a56-fd746e840c15
    type: title
    task:
      id: 2d0a1722-dbad-417a-8a56-fd746e840c15
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 240,
          "y": 1130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 96d277ca-89d0-4df3-8bae-13661e06dc44
    type: regular
    task:
      id: 96d277ca-89d0-4df3-8bae-13661e06dc44
      version: -1
      name: It worked!
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      value:
        simple: It worked!
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 933b027a-18e5-4a74-8c6c-82bc99af0963
    type: regular
    task:
      id: 933b027a-18e5-4a74-8c6c-82bc99af0963
      version: -1
      name: It did not work!
      description: Prints an error entry with a given message.
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      message:
        simple: test failed
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": 735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: b9c8fd25-2b34-4af9-a259-82b0cea0f021
    type: regular
    task:
      id: b9c8fd25-2b34-4af9-a259-82b0cea0f021
      version: -1
      name: Untitled Task
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1140,
        "width": 820,
        "x": 40,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: multiply_Test
dirtyInputs: true
