id: HelloWorld_Test
version: -1
vcShouldKeepItemLegacyProdMachine: false
name: HelloWorld_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a871ff6c-9c93-4d3a-800a-96d10f3a8ee9
    type: start
    task:
      id: a871ff6c-9c93-4d3a-800a-96d10f3a8ee9
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: fbc0b15d-a03c-4b64-84ad-5bcfd761d9ed
    type: regular
    task:
      id: fbc0b15d-a03c-4b64-84ad-5bcfd761d9ed
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 015bf1cb-ad67-4e50-9f3f-e9718156e36e
    type: regular
    task:
      id: 015bf1cb-ad67-4e50-9f3f-e9718156e36e
      version: -1
      name: Helloworld
      description: Hello command - prints hello to anyone.
      script: HelloWorld1|||helloworld-say-hello
      type: regular
      iscommand: true
      brand: HelloWorld1
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      extend-context:
        simple: test=
      name:
        simple: shlan
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 385
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 6e547088-b0ea-42c8-b340-db06796c0c6d
    type: condition
    task:
      id: 6e547088-b0ea-42c8-b340-db06796c0c6d
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: hello
            iscontext: true
          right:
            value:
              simple: Hello shailan
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 6196aec5-a0d3-4369-88f6-2c81bd4a1d0b
    type: title
    task:
      id: 6196aec5-a0d3-4369-88f6-2c81bd4a1d0b
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 910
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: a9ac1ab3-588b-4384-8a72-d536fd510a55
    type: regular
    task:
      id: a9ac1ab3-588b-4384-8a72-d536fd510a55
      version: -1
      name: It worked!
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      value:
        simple: It worked!
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 1df957a6-c629-47ab-b207-4050d39274cb
    type: regular
    task:
      id: 1df957a6-c629-47ab-b207-4050d39274cb
      version: -1
      name: It did not work!
      description: Prints an error entry with a given message.
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      message:
        simple: test failed
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": 735
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 920,
        "width": 820,
        "x": 40,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: multiply_Test
dirtyInputs: true
